baseURL = 'https://kathywang.ca/'
languageCode = 'en-us'
title = 'Kathy Wang Photography'
theme = 'hugo-theme-gallery'

[params]
  [params.author]
    name = 'Kathy Wang'
  description = 'Kathy Wang Photography - Portfolio'

# For GitHub Pages deployment
publishDir = 'docs'
